# Generated by Django 5.1.4 on 2025-01-17 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_collegeprofile_college_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collegeprofile',
            name='established_date',
            field=models.DateField(null=True),
        ),
    ]
