# Generated by Django 5.1.4 on 2025-01-19 09:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_collegeprofile_established_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='collegeprofile',
            name='about',
            field=models.TextField(null=True),
        ),
        migrations.CreateModel(
            name='CollegeInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courses', models.CharField(max_length=50)),
                ('fee_structure', models.DecimalField(decimal_places=2, max_digits=9)),
                ('requirements_for_enroll', models.CharField(max_length=200)),
                ('college_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'CollegeInfo',
                'verbose_name_plural': 'CollegeInfos',
                'db_table': 'College Info',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eduaction_level', models.CharField(choices=[('S.L.C./S.E.E.', 'S.L.C./S.E.E.'), ('+2', '+2'), ('Bachelor Degree', 'Bachelor Degree'), ('Masters', 'Masters')], max_length=30)),
                ('passed_year', models.DateField()),
                ('gpa', models.CharField(choices=[('Percntage', 'Percentage'), ('G.P.A.', 'G.P.A.')], max_length=10)),
                ('grade', models.DecimalField(decimal_places=2, max_digits=4)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'StudentInfo',
                'verbose_name_plural': 'StudentInfos',
                'db_table': 'Student Info',
                'managed': True,
            },
        ),
    ]
