# Generated by Django 5.1.4 on 2025-01-19 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_collegeprofile_about_collegeinfo_studentinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentinfo',
            old_name='eduaction_level',
            new_name='education_level',
        ),
    ]
