# Generated by Django 5.1.4 on 2025-01-19 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_rename_eduaction_level_studentinfo_education_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='collegeinfo',
            name='course_duration',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
