# Generated by Django 5.1.4 on 2025-01-25 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_collegeprofile_college_cover_collegeprofile_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='education_level',
            field=models.CharField(choices=[('S.L.C./S.E.E.', 'S.L.C./S.E.E.'), ('+2', '+2'), ('Bachelor Degree', 'Bachelor Degree'), ('Masters', 'Masters')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='gpa',
            field=models.CharField(choices=[('Percntage', 'Percentage'), ('G.P.A.', 'G.P.A.')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='grade',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='passed_year',
            field=models.DateField(null=True),
        ),
    ]
