# Generated by Django 5.1.4 on 2025-02-02 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_question_questioncategory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='options',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='main.question'),
        ),
    ]
