# Generated by Django 5.1.4 on 2025-02-04 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_options_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
                'db_table': 'College Location',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='collegeprofile',
            name='college_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='collegeinfo',
            name='courses',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='collegeprofile',
            name='college_location',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.collegelocation'),
        ),
    ]
