# Generated by Django 5.1.4 on 2025-02-04 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_collegelocation_collegeprofile_college_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collegeprofile',
            name='college_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.collegelocation'),
        ),
    ]
