# Generated by Django 5.1.4 on 2025-02-06 06:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_collegeprofile_college_location'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=15)),
                ('test_score', models.CharField(max_length=10)),
                ('application_status', models.CharField(default='Pending', max_length=50)),
                ('submitted_date', models.DateField(auto_now_add=True)),
                ('college_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.collegeprofile')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.collegeinfo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
