# Generated by Django 5.1.4 on 2025-02-07 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_application'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'managed': True, 'verbose_name': 'Application', 'verbose_name_plural': 'Applications'},
        ),
        migrations.AlterModelTable(
            name='application',
            table='Application List',
        ),
    ]
