# Generated by Django 5.1.4 on 2025-02-07 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_application_options_alter_application_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='college_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.collegeprofile'),
        ),
    ]
