# Generated by Django 5.1.4 on 2025-02-08 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_application_college_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='college_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.collegeprofile'),
        ),
    ]
