# Generated by Django 5.1.4 on 2025-02-08 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_alter_application_college_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='college_name',
            field=models.IntegerField(),
        ),
    ]
