# Generated by Django 5.1.4 on 2025-02-08 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_alter_application_college_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery img')),
                ('image_title', models.CharField(max_length=100)),
                ('image_desc', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
                'db_table': 'Gallery',
                'managed': True,
            },
        ),
    ]
