# Generated by Django 5.1.4 on 2025-02-08 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_alter_application_test_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collegeprofile',
            name='college_cover',
            field=models.ImageField(default='../static/images/profile-white.jpg', upload_to='college profle cover'),
        ),
    ]
