# Generated by Django 5.1.4 on 2025-02-08 17:57

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_alter_collegeprofile_college_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collegeprofile',
            name='about',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
