# Generated by Django 5.1.6 on 2025-09-08 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_alter_collegeprofile_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tes_img', models.ImageField(upload_to='testimonial/')),
                ('tes_name', models.CharField(max_length=100)),
                ('tes_message', models.TextField()),
                ('tes_title', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
                'db_table': 'Testimonials',
                'ordering': ['-created_at'],
                'managed': True,
            },
        ),
    ]
