# Generated by Django 5.1.6 on 2025-09-08 08:31

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Events Category',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='NewsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'News Category',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(max_length=50)),
                ('event_description', ckeditor.fields.RichTextField()),
                ('organizer', models.CharField(max_length=50)),
                ('poster', models.ImageField(upload_to='events/')),
                ('location', models.CharField(max_length=150)),
                ('event_date', models.DateField()),
                ('event_time', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_approved', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='main.eventcategory')),
            ],
            options={
                'db_table': 'Events',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title', models.CharField(max_length=50)),
                ('news_description', ckeditor.fields.RichTextField()),
                ('author', models.CharField(max_length=50)),
                ('author_img', models.ImageField(blank=True, null=True, upload_to='news/author/')),
                ('news_img', models.ImageField(upload_to='news/images/')),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_approved', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news', to='main.newscategory')),
            ],
        ),
    ]
