# Generated by Django 5.1.6 on 2025-09-09 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_eventcategory_newscategory_event_new'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collegeprofile',
            name='college_cover',
            field=models.ImageField(default='def_profile.jpeg', upload_to='college profle cover'),
        ),
        migrations.AlterField(
            model_name='collegeprofile',
            name='college_profile_img',
            field=models.ImageField(default='def_profile.jpeg', upload_to='college profile img'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='profile_img',
            field=models.ImageField(default='def_profile.jpeg', upload_to='student profile img'),
        ),
    ]
