# Generated by Django 5.1.6 on 2025-09-09 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_alter_collegeprofile_college_cover_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='grade',
            field=models.CharField(default='', max_length=10),
        ),
    ]
