# Generated by Django 5.1.6 on 2025-09-10 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_alter_studentinfo_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='gpa',
            field=models.IntegerField(default='', max_length=10, null=True),
        ),
    ]
