# Generated by Django 5.1.6 on 2025-09-10 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_alter_studentinfo_gpa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='gpa',
            field=models.DecimalField(decimal_places=2, default='', max_digits=5, null=True),
        ),
    ]
